
on:
  push:
    branches:
      - main
      - master

name: Jira Example

jobs:
  a-failing-job:
    runs-on: ubuntu-latest
    steps:
    - name: Failing step
      run: exit 1
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: https://rakshitmohan99.atlassian.net
        JIRA_USER_EMAIL: rakshitmohan99@gmail.com
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create Jira issue on job failure
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: TEST
        issuetype: Task
        summary: Build failed for ${{ github.repository }}
